### PR TITLE
Switch to fuzzaldrin-plus

### PR DESCRIPTION
**Pull request by mehcode**
@chuckhendo Continued from #38

### CODE REVIEW

**Comment by chuckhendo** [comment]
To answer your question from the other PR @mehcode - yes, I can write some specs for this

**Comment by mehcode** [comment]
@chuckhendo Did you want to finish this?

**Comment by chuckhendo** [comment]
@mehcode Yes! Sorry, got really busy with some other stuff. Should have some time this week to work on it

**Comment by jeancroy** [comment]
> It's a shame that SelectListView doesn't use the newer fuzzy matcher yet. It also probably won't ever as Atom is moving away from space-pen.

The problem I see is routing a config option to SelectListView. But as fuzzaldrin-plus is becoming default option without much push back it may change default there too.

For example language selection menu in bottom left corner still use classic fuzzaldrin, because there's no way to route an option there.

An in between solution would be the split populate data VS ui role then overide only data part, that will be cleaner.

**Comment by chuckhendo** [comment]
No idea how I accidentally closed this... I'm working on this now

**Comment by chuckhendo** [comment]
@mehcode any specific tests you're looking for here? I'm basically doing a functional UI test (showing the view, entering text, checking the results to make sure they are correct, etc)... but I'm pretty sure any tests I write are going to fail when regression testing, since the matching algorithm is now different.

**Comment by mehcode** [comment]
@chuckhendo I'm just going to merge it in. It works fine. Thanks for the contribution. If you'd like to add tests at a later time, go ahead.

**Pull request merged**
